# Google Cloud Platform - Using Machine Learning APIs  ).

This is an upgraded Python revision of [this notebook](https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/CPB100/lab4c/mlapis.ipynb).

This notebook originally was being processed using DataLab on the Google Cloud Platform.  This particular incarnation of the notebook is for running on Google Colaboratory which I am trying out for the first time.

### Security

First things first - we need to authenticate against the Google Cloud APIs.

#### Getting a Google API Credential.

First, visit <a href="http://console.cloud.google.com/apis">API console</a>, choose "Credentials" on the left-hand menu.  Choose "Create Credentials" and generate an API key for your application. You should probably restrict it by IP address to prevent abuse, but for now, just  leave that field blank and delete the API key after trying out this demo.

Then, when you have your key, you will enter it in this first executable cell:

In [156]:
import sys
import json
import pandas as pd
import skimage.io
import os
import numpy as np


In [179]:
def create_service():
    return


def list_bucket(bucket):
    listdir = os.listdir(bucket)
    for i in range(0, len(listdir)):
        listdir[i]="images/"+listdir[i]
        
    files=pd.DataFrame()
    files['image_path']=listdir
    return files

def strip_filepath(infiles):
    infiles=infiles.image_path.str.split('/').str[-1]
    files=pd.DataFrame()
    files['ImageID']=infiles
    files=files.ImageID.str.split('.').str[0]
    return(files)

def build_master_df():
    BUCKET='C:\\WPI\\MachineLearning\\FinalProject_Local\\images'
    BBOX='C:\\WPI\\MachineLearning\\FinalProject_Local\\bbox_test.csv'
    
    #THESE FUNCTIONS ARE USED TO ESTABLISH CONNECTION WITH GCP AND EXTRACT ARRAY OF ALL IMAGES
    create_service()
    files=list_bucket(BUCKET)
    
    #STRIP THE PATH INFO PROVIDED TO DETERMINE OPENIMAGES IMAGEID
    imageid=strip_filepath(files)
    files['ImageID']=imageid
    
    #READ IN BOUNDING BOX
    bbox=pd.read_csv(BBOX)
    
    #MERGE LIST OF ALL FILES WITH BOUNDING BOX INFORMATION
    df_all = pd.merge(files, bbox, on='ImageID', how='inner')
    return(df_all)
    
def process_image(filename):
    image_raw=np.array(skimage.io.imread(filename))
    img_size=image_raw.size 
    images_flat=image_raw.ravel()
    images_color = images_flat.reshape(-1, img_size)
    return(images_color)



In [195]:
def main():
    df_all=build_master_df()
    
    '''
    n_images=len(df_all.index)
    image_cnt=0
    batch_size=5

    #while image_cnt<n_images:
    while image_cnt<5:
        batch_cnt=0
        while batch_cnt<batch_size:
            case=df_all.iloc[image_cnt]
            print('image_filename')
            print(case.image_path)
            image_vec=process_image(case.image_path)
            df_all.loc[image_cnt,'image_vec'] = image_vec
            #df[i]=image_vec.toarray().tolist()
            batch_cnt+=1
            image_cnt+=1
        #image_vec=process_image()
        image_cnt+=1
    '''
main()

image_filename
images/BMHF3758.JPG
[[[158 168  97]
  [152 162  93]
  [159 166  99]
  ...
  [ 77 111 185]
  [ 77 111 185]
  [ 78 112 184]]

 [[157 167  98]
  [152 162  93]
  [157 163  99]
  ...
  [ 77 111 185]
  [ 77 111 183]
  [ 77 111 183]]

 [[154 164  95]
  [148 157  90]
  [151 157  93]
  ...
  [ 77 111 185]
  [ 77 111 183]
  [ 77 111 183]]

 ...

 [[149 125  91]
  [148 125  91]
  [148 126  89]
  ...
  [247 219 182]
  [247 219 182]
  [246 218 181]]

 [[149 125  91]
  [149 126  92]
  [149 126  92]
  ...
  [247 219 180]
  [247 219 180]
  [247 219 180]]

 [[149 125  91]
  [149 126  92]
  [150 127  93]
  ...
  [248 220 181]
  [248 220 181]
  [247 219 180]]]
[[158 168  97 ... 247 219 180]]


ValueError: Must have equal len keys and value when setting with an ndarray